### ISSUE TITLE
[개발요청] 홈 - 타이틀배너 2개 롤링 적용

### ISSUE THREAD

**Issue by jy-work** [jy-work/ransomstop#1]
![image](https://user-images.githubusercontent.com/76195862/102713452-b37dcf00-430b-11eb-9f20-af3475cba29e.png)

## 요청사항
- [x] 2개의 배너 롤링 되도록 수정

**Comment by seungwan** [comment]
@jy-work 
Home> 메인 루프 이미지
아직 RSM 이미지와 텍스트는 적용이 안되어 있던데.. 
다시 PDF와 이미지 첨부합니다. 
[Home_MainLoofIMG.zip](https://github.com/jy-work/ransomstop/files/5723223/Home_MainLoofIMG.zip)
[RansomStopSite_HomeMainIMG_Loop_20201113 사본.pdf](https://github.com/jy-work/ransomstop/files/5723225/RansomStopSite_HomeMainIMG_Loop_20201113.pdf)
