### ISSUE TITLE
RansomStop 가오픈 예정 메뉴 (2020.12.23)

### ISSUE THREAD

**Issue by seungwan** [jy-work/ransomstop#10]
### RansomStop 가오픈 예정 메뉴
- home
- 개인/소호용 / RansomStop Pro
- 개인/소호용 / RansomStop for Server
- 기업용 / RSM
- 기업용 / eG Enteprise
- 고객지원 / 제품문의/상담 (폼메일)
- 노웨어소프트 (회사소개/연혁/찾아오시는길)
- 노웨어소프트 / 인재채용(내비 배너; 팝업 페이지)
이상 8페이지

@jy-work 
1. 해당 8페이지 내비게이션메뉴 동일하게 적용. (나머지 서브메뉴 숨기기, 상호링크 적용)
2. 랜섬웨어연구소 대메뉴 링크막기(#)
3. 노웨어소프트 (회사소개, 연혁, 찾아오시는길 앵커링크 적용)
4. 모든 페이지 하단 **제품상담 바로가기**는 고객지원 제품문의/상담 페이지로 이동
5. 인재채용 페이지 퍼블리싱 및 팝업처리 필요

**Comment by seungwan** [comment]
Home 
/노웨어소프트 안티랜섬웨어/ 제품 소개 박스 링크 연결

개인/소호형 바로가기 > RansomStopPro 페이지
기업형 바로가기 > RSM 페이지

**Comment by seungwan** [comment]
@jy-work 
각 제품별 슬라이드 이미지(스크린샷) 첨부 > 적용 요청
[SiteScreenShot.zip](https://github.com/jy-work/ransomstop/files/5728473/SiteScreenShot.zip)

**Comment by seungwan** [comment]
모든 제품문의/ 상담문의는 고객센터/제품문의상담 페이지로 이동
다운로드(평가판) > 네이버 소프트웨어 ransomStop [새창으로]
[https://software.naver.com/software/summary.nhn?softwareId=GWS_003358](url)

**Comment by jy-work** [comment]
어제 말씀드린 제품소개 롤링(반응형)과 서버 로고 제외하고 수정 완료하였습니다.
