### ISSUE TITLE
[개발요청] 네비게이션 배너로 변경

### ISSUE THREAD

**Issue by jy-work** [jy-work/ransomstop#5]
## 요청사항
네비게이션 링크 - 배너로 변경
- [x] 인재채용
- [x] 평가판

**Comment by jy-work** [comment]
작업 커밋 : https://github.com/jy-work/ransomstop/commit/dd347eb0ee15ed18ac3d2897eb0081e6d279dfc6

**Comment by seungwan** [comment]
@jy-work 
링크 수정
**인재채용**은 별도 모달팝업 또는 전체 팝업으로 별도페이지(새창) 링크 (RansomStopSite_Popup_Recruit_20201221.pdf)
**평가판**은 네이버 소프트웨어 링크가 맞는데 링크를 새창으로 올려야 함.

**Comment by jy-work** [comment]
수정완료
