### ISSUE TITLE
[기획문의] 텍스트 복붙이 안되는 이슈

### ISSUE THREAD

**Issue by jy-work** [jy-work/ransomstop#7]
![image](https://user-images.githubusercontent.com/76195862/102722432-6c600000-4344-11eb-8df5-f0d11533896c.png)

에스코어 드림 폰트 모두 설치한 상태인데, 다시 복붙이 안되고 있습니다.
word로 변환해서 봐도 텍스트가 모두 깨지는데, 혹시 텍스트가 살아있는 다른 파일로 전달해주실 수 있을까요?

**Comment by jy-work** [comment]
![image](https://user-images.githubusercontent.com/76195862/102722919-d4fcac00-4347-11eb-89c2-27e77f323a71.png)

이런 페이지의 변경된 텍스트 적용 하려는데 안되네요

**Comment by seungwan** [comment]
#9 
@jy-work 위에 페이지 참고하세요.
